import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { NavbarProvider } from "@/context/contextApi";


export const metadata: Metadata = {
  title: "Shiploan | Manage your loans",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="relative h-full min-h-screen"
      >
        <NavbarProvider >

          <Navbar />
          {children}
          <Footer></Footer>
        </NavbarProvider>
      </body>
    </html>
  );
}
